# inspired from https://circleci.com/blog/publishing-a-python-package/

version: 2.1
jobs:
  check_code_health_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: "Install Git"
          command: sudo apt-get update && sudo apt-get install -y git
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            pip install -r requirements-dev.txt
      - run:
          name: "Code linting (Flake, black & isort)"
          command: pipenv run flake8 .
      - run:
          name: "Checking typing with mypy"
          command: pipenv run mypy .
      - run:
          name: "Unit tests"
          command: pipenv run pytest -v

  build_and_install_package:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: "Create whl and use pipenv to install it"
          command: |
            python setup.py sdist bdist_wheel
            pip install dist/letxbe-0.1.0-py3-none-any.whl

workflows:
  check_code_health_test_and_build:
    jobs:
      - check_code_health_test
      - build_and_install_package:
          requires:
            - check_code_health_test