"""

A `Target` is a `Document` that can be processed to generate and store a `Prediction` or `Feedback`.

"""
from typing import Literal, Optional

from pydantic import BaseModel

from .artefact import ArtefactConnectionMixin
from .document import DocumentMixin, StatusMixin, WithParentMixin
from .label import Current, Feedback, Prediction


class TargetMixin(BaseModel):
    """
    Information specific to a `Target` and not shared with `Artefact`.

    role: should be equal to `None`, as opposed to an `Artefact`
    prediction: `Prediction` containing information generated by providers about the document.
    feedback: `Feedback` containing aggregated confirmations, deletions or modifications
        of `TargetMixin.prediction` values.
    current: contains only information that should be considered true,
        by combining `Feedback` and `Prediction`.
    """

    role: Literal[None] = None
    prediction: Prediction = Prediction()
    feedback: Optional[Feedback] = None
    current: Current = Current()


class Target(
    DocumentMixin, TargetMixin, WithParentMixin, StatusMixin, ArtefactConnectionMixin
):
    """
    Information about a `Target` that is available when accessing it directly.
    """
